# Generated by Django 5.1.1 on 2024-09-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("purchase_date", models.DateField()),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
