# Generated by Django 4.1.13 on 2024-09-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_customer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
