# Generated by Django 4.1.13 on 2024-09-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_sales"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sales",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="sales",
            name="product",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Sales",
        ),
    ]
